---
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
  - npm test
